name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'crawl-game/crawl-0.25/**'
      - '.github/workflows/crawl25-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'crawl-game/crawl-0.25/**'
      - '.github/workflows/crawl25-build.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: crawl-game/crawl-0.25
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crawl25:$(date +%s) --build-arg crawlversion=crawl-0.25
